#!/bin/sh
# /etc/init.d/rcS
/bin/mount -t proc     proc /proc
/bin/mount -t sysfs    sysfs /sys
/bin/mount -t devtmpfs dev  /dev
echo /sbin/mdev > /proc/sys/kernel/hotplug
/sbin/mdev -s
/bin/mount -a
/bin/hostname -F /etc/hostname
/sbin/ifconfig lo 127.0.0.1 up
dmesg -n 3 2>/dev/null || true
echo "========================================"
grep PRETTY_NAME /etc/os-release
echo " Kernel: $(uname -r)"
echo "========================================"
for script in /etc/init.d/S[0-9]*; do
    [ -x "$script" ] && "$script" start
done